name: CI development

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18']
        application-name: ['superhero-battle-backend']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Folder
        run: cd ${{ matrix.application-name }}
      
      - name: Install dependencies
        run: go mod download

      - name: Compile
        run: go build -o app .
